addSbtPlugin("com.jsuereth"      %  "sbt-pgp"               % "1.1.0")
addSbtPlugin("com.github.gseitz" %  "sbt-release"           % "1.0.7")
addSbtPlugin("org.xerial.sbt"    %  "sbt-sonatype"          % "2.0")
addSbtPlugin("com.47deg"         %  "sbt-microsites"        % "0.7.13")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"            % "0.3.3")
